---
- name: Set rails container id
  shell: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" ps -q rails | head -1
  register: rails
  args:
    chdir: "{{ current_path }}"

- name: Precompile assets
  command: docker exec -i "{{ rails.stdout }}" bin/rake assets:precompile
  args:
    chdir: "{{ current_path }}"
...
