---
- name: Set rails container id
  shell: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" ps -q rails | head -1
  register: rails
  args:
    chdir: "{{ current_path }}"

- name: Rake db migrate
  command: docker exec -it "{{ rails.stdout }}" sh -c 'bundle exec rake db:migrate'
  args:
    chdir: "{{ current_path }}"

- name: Rake db seed
  command: docker exec -it "{{ rails.stdout }}" sh -c 'bundle exec rake db:seed'
  args:
    chdir: "{{ current_path }}"
...
