---
- name: Set rails container id
  shell: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" ps -q rails | head -1
  register: rails
  args:
    chdir: "{{ current_path }}"

- name: Rake db migrate
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:migrate
  args:
    chdir: "{{ current_path }}"

- name: Rake db seed
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:seed
  args:
    chdir: "{{ current_path }}"
...
