---
- name: Generate Gemfile.lock
  command: docker run --rm -v "{{ current_path }}":/usr/src/app -w /usr/src/app ruby bundle
  args:
    chdir: "{{ current_path }}"

- name: Build new rails container
  command: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" build
  args:
    chdir: "{{ current_path }}"

- name: Up docker services
  command: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" up -d
  args:
    chdir: "{{ current_path }}"

- name: Set rails container id
  shell: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" ps -q rails | head -1
  register: rails
  args:
    chdir: "{{ current_path }}"

- name: Rake db migrate
  command: docker exec -it "{{ rails.stdout }}" sh -c 'bundle exec rake db:migrate'
  args:
    chdir: "{{ current_path }}"

- name: Rake db seed
  command: docker exec -it "{{ rails.stdout }}" sh -c 'bundle exec rake db:seed'
  args:
    chdir: "{{ current_path }}"

- name: Precompile assets
  command: docker exec -it "{{ rails.stdout }}" sh -c 'bundle exec rake assets:precompile'
  args:
    chdir: "{{ current_path }}"

- name: Restart rails docker container
  command: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" restart rails
  args:
    chdir: "{{ current_path }}"
...
