---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Install apt-transport-https
  apt:
    pkg: "apt-transport-https"
    force: yes
    state: present

- name: Install ca-certificates
  apt:
    pkg: "ca-certificates"
    force: yes
    state: present

- name: Install docker-engine
  apt:
    pkg: "docker.io"
    state: present

- name: Install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/run.sh"
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: root
    group: root

- name: Install git-core
  apt:
    pkg: "git-core"
    state: present

- name: Install htop
  apt:
    pkg: "htop"
    state: present
...
