---
- name: Create user
  user:
    name: "{{ app_name }}"
    createhome: yes
    shell: /bin/bash
    generate_ssh_key: no
    groups: docker
    append: yes

- name: Copy dev ssh public key
  authorized_key:
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    user: "{{ app_name }}"
    state: present
...
