---
- name: Export structure.sql
  copy:
    src: structure.sql
    dest: "{{ db_path }}/structure.sql"

- name: Restart rails containers
  command: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" restart rails
  args:
    chdir: "{{ current_path }}"

- name: Set rails container id
  shell: docker-compose -f docker-compose.prod.yml -p "{{ app_name }}" ps -q rails | head -1
  register: rails
  args:
    chdir: "{{ current_path }}"

- name: Rake db drop
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:drop
  args:
    chdir: "{{ current_path }}"

- name: Rake db create
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:create
  args:
    chdir: "{{ current_path }}"

- name: Load data from structure.sql
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:structure:load
  args:
    chdir: "{{ current_path }}"

- name: Rake db migrate
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:migrate
  args:
    chdir: "{{ current_path }}"

- name: Rake db seed
  command: docker exec -i "{{ rails.stdout }}" bin/rake db:seed
  args:
    chdir: "{{ current_path }}"
...
