---
- name: Setup hosts
  hosts: webservers
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: Install python2
      raw: apt-get update && apt-get -y install python-minimal
  roles:
    - {role: setup}
...
